### ISSUE TITLE
LLD doesn't support /filealign

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#123]
This will be necessary for making smaller binaries (specifically DXT).

There's an attempt to fix this upstream in https://reviews.llvm.org/D62124
It will probably take a long time before this is integrated and available in stable releases.

**Comment by JayFoxRox** [comment]
This has landed upstream: https://github.com/llvm-mirror/lld/commit/b6404d73804920cd2977f2ec1268c316fd7722cf

*(See https://github.com/XboxDev/nxdk/issues/119#issuecomment-496124339 for estimates when it will be usable to us)*

**Comment by thrimbor** [comment]
Landed upstream over a year ago, so no need to keep this open anymore imho.
