### ISSUE TITLE
LLD doesn't support /align

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#124]
This will be necessary for making smaller binaries (specifically DXT).

This needs to be fixed upstream.

I've explained what's necessary in https://github.com/JayFoxRox/lld/issues/2

**Comment by thrimbor** [comment]
This was implemented in https://github.com/llvm/llvm-project/commit/e6a33e1f11bfd0cdedcd6ea71c378d6611b3922c#diff-997c507a3d001706c940347b6e136ac5350af92b727aa38101d810863b51fa48.
