### ISSUE TITLE
lwip doesn't read EEPROM network configuration

### ISSUE THREAD

**Issue by dracc** [XboxDev/nxdk#134]
Issue transfered from [the Wiki](https://github.com/XboxDev/nxdk/wiki/Want-to-help%3F).

**Comment by JayFoxRox** [comment]
There's also an issue about this in nxdk-rdt: https://github.com/XboxDev/nxdk-rdt/issues/10

**Comment by JayFoxRox** [comment]
Should this be closed by https://github.com/XboxDev/nxdk/pull/575 ?
While it isn't taken care of by lwip itself, it's being handled by an nxdk specific API now.

**Comment by dracc** [comment]
> Should this be closed by #575 ?
> While it isn't taken care of by lwip itself, it's being handled by an nxdk specific API now.

I mean, it's still not reading EEPROM settings, but seeing as noone else seemingly does either, it's probably for the better.
