### ISSUE TITLE
Broken video output on 1.6

### ISSUE THREAD

**Issue by dracc** [XboxDev/nxdk#145]
Samples utilizing SDL gives black output or flickering garbage. "Regular" debug-text only output works but flickers to black.

System;
Xbox 1.6
Video region NTSC-M
Component cables

**Comment by dracc** [comment]
Semi-false alarm?
Works fine with a different monitor.

**Comment by dracc** [comment]
I haven't had an issue since back when this was reported. Closing

**Comment by JayFoxRox** [comment]
Marked as invalid as this problem probably never existed in the first place.
