### ISSUE TITLE
lwip: Use BSD socket API

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#15]
The existing code uses the lwip netbuf interface, however, for compatibility with existing code and ease of use, we should rewrite the httpd example to use the BSD style socket API.

We should also make sure that the BSD style API works flawless.
nxdk-rdt has a lot of issues with the netbuf API, however, it is still unclear where exactly these issues stem from (be it nxdk-rdt, lwip or the Xbox specific network driver). With the BSD API we could test behaviour on other platforms and we will not have to worry about splitting or joining the network packets manually like we currently do.

**Comment by thrimbor** [comment]
Resolved in #151.
