### ISSUE TITLE
Brew command for macOS in Readme doesn't work

### ISSUE THREAD

**Issue by einsteinx2** [XboxDev/nxdk#152]
I tried running `brew install llvm --with-lld --with-clang` but received the error `Error: invalid option: --with-lld`. I tried removing the `--with-lld` flag and then got the error `Error: invalid option: --with-clang`.

I finally went ahead and just ran `brew install llvm` and was able to successfully build and run various samples. I guess something changed in the Homebrew repository since the Readme was written and those options no longer need to be specified manually.

Also as a side note, the git clone commands can be replaced with a single command:
`git clone --recursive https://github.com/XboxDev/nxdk.git`

**Comment by thrimbor** [comment]
The readme is very outdated, we recommend using the wiki, which you should be able to edit if it's incorrect, too.
Also see #73 and #143.

**Comment by einsteinx2** [comment]
Thanks, just updated the Wiki pages for those two commands.
