### ISSUE TITLE
LLVM 9 crashes when linking in debug mode

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#176]
It is currently known to affect macOS and Linux, but it probably also affects other platfoms.

To avoid running into this issue in our CI, #173 disabled debug builds for our sample code.

**Comment by dracc** [comment]
https://hastebin.com/lomigitefo.coffeescript

Tested on Debian Linux with lld-9.

**Comment by thrimbor** [comment]
I have successfully bisected the issue and submitted a patch upstream: https://reviews.llvm.org/D68352

**Comment by thrimbor** [comment]
The patch has now landed https://github.com/llvm/llvm-project/commit/c3c5e0fbbf7689aa841e9ad218ee06084554e7e6

**Comment by JayFoxRox** [comment]
Thanks! We should still wait until LLVM 9.0.1 is released (and tested) before closing this issue.

**Comment by thrimbor** [comment]
LLVM 9.0.1 was released ~two weeks ago, but it doesn't include the patch, lld still crashes. LLVM 10 is supposed to get released on February 26th.

**Comment by GXTX** [comment]
Appears to be properly upstreamed. Untested on 10, tested on 11 working with `DEBUG = y`. Should this issue stay open?

**Comment by thrimbor** [comment]
It's fixed in LLVM 10 and up. For people still running an OS that ships with LLVM 9 I recommend using the nxdk Docker image.
