### ISSUE TITLE
llvm-lib is not automatically found on Ubuntu in LLVM 6

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#196]
As we noticed in https://github.com/XboxDev/nxdk/pull/156#issuecomment-537164003, Ubuntu 18.04 LTS seems to use LLVM 6 by default. However, in their LLVM 6 package not all binaries are found in `PATH`, even though they are still installed.

In https://github.com/XboxDev/nxdk/pull/156#issuecomment-538462217 I've additionally described that upstream probably won't fix it themselves.
They did fix it for LLVM 7 in the past but do not plan to backport the change to LLVM 6.

Possible workarounds include:
- Installing a more recent LLVM version (recommended)
- `PATH=$PATH:/usr/lib/llvm-6.0/bin` so the binaries are found (recommended)
- Manually creating a symbolic link per-binary

A workaround must be added to the wiki ([here](https://github.com/XboxDev/nxdk/wiki/Install-the-Prerequisites#ubuntu)). Ideally to install a newer LLVM altogether.

This issue might also affect other Debian distributions.

**Comment by Natetronn** [comment]
Thanks! I ran into this problem just now. I didn't have success with the first work around (had trouble installing llvm-9; kept saying something about unmet dependency llvm-9-dev, even though I installed that as well) but, the second working around seemed to have worked.

**Comment by dracc** [comment]
Preferable way to create symlink on Debian-based distros such as Ubuntu:
`sudo update-alternatives --install /usr/bin/llvm-lib llvm-lib /usr/bin/llvm-lib-6.0 10`

**Comment by thrimbor** [comment]
While Ubuntu 18.04 LTS is still supported, they don't plan to fix this. For people still affected by this issue I recommend to either switch to 20.04 LTS, or, if that's not a fitting solution for them, use the nxdk Docker image.

**Comment by Margen67** [comment]
This occurs with GitHub Actions on 20.04:
https://github.com/Margen67/xbox_kernel_test_suite/runs/2249786204?check_suite_focus=true#step:6:492
Same job, but LLVM is added to path:
https://github.com/Margen67/xbox_kernel_test_suite/runs/2249786190?check_suite_focus=true

**Comment by thrimbor** [comment]
@Margen67 It looks like you're not installing the dependencies.

**Comment by Margen67** [comment]
> 
> 
> @Margen67 It looks like you're not installing the dependencies.

You were right. Installing `lld` and `llvm` fixed the issue.

**Comment by JayFoxRox** [comment]
> While Ubuntu 18.04 LTS is still supported, they don't plan to fix this. For people still affected by this issue I recommend to either switch to 20.04 LTS, or, if that's not a fitting solution for them, use the nxdk Docker image.

What's the lowest supported LLVM version now?
There's also https://github.com/XboxDev/nxdk/issues/119#issuecomment-496124339 which requires LLVM 9 or higher.

**Comment by thrimbor** [comment]
The oldest LLVM version that, to the best of my knowledge, does not have any issues in one of the distributions, is LLVM 10 (<9 can't build import libs, 9 crashes with debug builds). It's also the default version on Ubuntu 20.04 LTS.
I didn't find any documentation of what the LLVM project considers to be a supported release, but it seems like they only release bugfix versions until the next major version is released (newest one is LLVM 12, released last Wednesday).
