### ISSUE TITLE
Sample code uses SCREEN_WIDTH and SCREEN_HEIGHT

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#207]
The SDL sample uses internals from hal/debug.c by manually declaring `extern` variables:

https://github.com/XboxDev/nxdk/blob/72ef089db22f7b1908e6ba36937895506d21e6c8/samples/sdl/main.c#L178-L180

used here:

https://github.com/XboxDev/nxdk/blob/72ef089db22f7b1908e6ba36937895506d21e6c8/samples/sdl/main.c#L286-L290

These are internals of debug.c which should not be used. Additionally, debug.c should be considered deprecated by now.

Instead, the sample should query the current mode using `XVideoGetMode` (beware of #149).

Note that this might interact with https://github.com/XboxDev/nxdk-sdl/issues/13

The other samples should also be reviewed. There's also other variables that might be used, such as `SCREEN_REFRESH` or `SCREEN_BPP` - neither of those should be used.

**Comment by JayFoxRox** [comment]
I have already implemented this in https://github.com/JayFoxRox/nxdk/pull/77

I'm just waiting for another PR that's currently in review, which would conflict with these changes.
I'll create the follow-up PR (which will close this issue) in the near future.

**Comment by dracc** [comment]
This can (probably) be closed thanks to #398 .
