### ISSUE TITLE
Build fails when linking main.exe

### ISSUE THREAD

**Issue by sogilbert** [XboxDev/nxdk#245]
Hello. When I try to build on Ubuntu 18.04 LTS or Windows 10 with MinGW 64-bit, I get this error message:

[ CC       ] /home/xxxx/nxdk/lib/hal/input.obj
[ CC       ] /home/xxxx/nxdk/lib/hal/io.obj
[ CC       ] /home/xxxx/nxdk/lib/hal/led.obj
[ CC       ] /home/xxxx/nxdk/lib/hal/video.obj
[ CC       ] /home/xxxx/nxdk/lib/hal/xbox.obj
[ LIB      ] /home/xxxx/nxdk/lib/libnxdk_hal.lib
[ CC       ] /home/xxxx/nxdk/lib/usb/host/ohci-hcd.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/message.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/hcd.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/hcd-pci.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/hub.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/usb.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/config.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/urb.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/buffer_simple.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/core/usb-debug.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/sys/BootUSB.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/sys/linuxwrapper.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/sys/xpad.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/sys/xremote.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/sys/usbkey.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/sys/usbmouse.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/misc/misc.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/misc/pci.obj
[ CC       ] /home/xxxx/nxdk/lib/usb/misc/malloc.obj
[ LIB      ] /home/xxxx/nxdk/lib/libnxdk_usb.lib
[ LD       ] main.exe
lld: error: libpdclib.lib(crt0.obj): undefined symbol: _main
Makefile:122: recipe for target 'main.exe' failed
make: *** [main.exe] Error 1

Could you help me with this? Thank you.

**Comment by dracc** [comment]
You're building using only the makefile in the nxdk root dir, right? You need to compile a project that provides `main`. Try compiling one of the samples instead.

**Comment by thrimbor** [comment]
Seems like a user error and no reaction from the issue author for a week, closing.

@sogilbert If you're still encountering build issues, please report back with as many details as possible (i.e. full build log, the exact command you used to build, the path where you executed it etc. - basically everything we'd need to reproduce the issue).
