### ISSUE TITLE
SDL: cant find matching render device.

### ISSUE THREAD

**Issue by Promises** [XboxDev/nxdk#27]
Is sdl 2 not properly implemented, or is it my setup thats wrong?

**Comment by mborgerson** [comment]
SDL support is *very* barebones. Does the sample (samples/sdl) work for you?

**Comment by Promises** [comment]
yeah thay do, i think some failed, a while since i tested, working on vita instead for now.

**Comment by dracc** [comment]
Is this issue ready to be closed?

**Comment by JayFoxRox** [comment]
There's no good way to reproduce this, and this issue is very old.

The SDL issue probably persists, but we can create a new issue with more information if necessary.
I'm going to close this issue for now.

Closed.
