### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by sam-itt** [XboxDev/nxdk#276]
Hi,

I'm trying to build to toolchain and I get this:
[ LD       ] main.exe
lld: error: undefined symbol: _main
>>> referenced by libpdclib.lib(crt0.obj):(_main_wrapper)

I'm running gentoo, llvm and lld 8.0.1. 
Any idea of what I can do ?

**Comment by JayFoxRox** [comment]
The Makefile is to be included by a project. `make` in the top-level will fail because you don't have an application entry-point.

Try `make -C samples/mesh` or `cd samples/mesh; make`. The output will be in samples/mesh/bin/default.xbe and samples/mesh/mesh.iso

**Comment by sam-itt** [comment]
Works great, thanks.
