### ISSUE TITLE
"-Os" optimization flag breaks pbkit

### ISSUE THREAD

**Issue by thrimbor** [XboxDev/nxdk#291]
Adding `-Os` to `NXDK_CFLAGS` breaks pbkit, making it not initialize at all or print error messages when running in xqemu. Running on a real Xbox seems to always result in an error message. Other optimization flags weren't tried yet.

Screenshots from running in xqemu are below. I currently don't have a way to grab a readable picture of the error message from my Xbox, so I'm not providing that.

![Screenshot_20200124_003804](https://user-images.githubusercontent.com/1339483/73034462-489aee00-3e45-11ea-9128-717dba9bc3c8.png)

![Screenshot_20200124_003826](https://user-images.githubusercontent.com/1339483/73034466-4c2e7500-3e45-11ea-9fd9-ef3d4a18b9f8.png)

**Comment by mborgerson** [comment]
Likely culprit is compiler caching this value: https://github.com/XboxDev/nxdk/blob/a944b38b1bdd1753dc484305e061f5eb98a05c74/lib/pbkit/pbkit.c#L3227

We should be using the `volatile` keyword (likely in other places too).

**Comment by JayFoxRox** [comment]
This loop also should be investigated:

https://github.com/XboxDev/nxdk/blob/a944b38b1bdd1753dc484305e061f5eb98a05c74/lib/pbkit/pbkit.c#L1118-L1137

Currently the compiler can assume the loop-condition to be always false, so it would never do it more than once. Not only will it need volatile, but also probably a cache flush for the GPU to see those RAM values? To be honest, I'm not even sure how this code is supposed to work.

Other code using `VIDEO_BASE` should probably be reviewed. Although most of it appears to be reads outside of MMIO regions (so ordering is not relevant and redundant writes aren't required either).
