### ISSUE TITLE
`NXDK_CXX` Makefile option is not documented

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#311]
At least the hello++ sample should contain `NXDK_CXX = y` so users are made aware that C++ support needs to be enabled explicitly (at least for now).

**Comment by Teufelchen1** [comment]
I'm unable to find _any_ information about `NXDK_CPP`. In fact, when searching through the repo, I found that `NXDK_CPP` is nowhere mentioned. How does setting a var that never gets checked lead to C++ support? What am I missing?
Maybe its some Makefile magic, like `($projectname)_CPP`?

**Comment by JayFoxRox** [comment]
I made an error when creating this issue; the option is actually called `NXDK_CXX`, not `NXDK_CPP`:
https://github.com/XboxDev/nxdk/blob/9a5e86d860eccc144000bdddb7a13f7dc1ff6df3/Makefile#L93-L95

**Comment by JayFoxRox** [comment]
Closed by #366 - implicit documentation is good enough for now. There's also #367 as a catch-all issue now for explicit documentation.
