### ISSUE TITLE
Fix networking packet size issue

### ISSUE THREAD

**Issue by mborgerson** [XboxDev/nxdk#35]
Seems like packets of size greater than 128 bytes cause issues, making the network stack *almost* useless. It's probably not too complicated, just needs investigation.

**Comment by JayFoxRox** [comment]
We have a couple of network users by now, and nobody seems to have problems with this. I don't think this problem ever existed (I assume it was bugs in how lwip was used).

If this problem really exists, create a new issue, or leave a message so we can re-open this discussion.

Closed.
