### ISSUE TITLE
Setup CI build system

### ISSUE THREAD

**Issue by mborgerson** [XboxDev/nxdk#36]
Something like [Travis CI](https://travis-ci.org/) would be great to have to test the build on PR. Maybe [AppVeyor](https://www.appveyor.com/) for Windows nightly build downloads.

**Comment by JayFoxRox** [comment]
I believe we can close this? We have Windows, macOS and Linux CI via Travis now (See #84 and #157).

We only have to add CI badges to README at this point.
Distributing binaries wouldn't be beneficial for this project, as most compile deps are also required later on.

**Comment by thrimbor** [comment]
#246 added badges, so I think it's fine if I close this now.
