### ISSUE TITLE
nxUnmountDrive() returns true even in case of error

### ISSUE THREAD

**Issue by kosmas12** [XboxDev/nxdk#379]
As said on the title, nxUnmountDrive() returns true even if there was an error when unmounting. Here is the code that does this: https://github.com/XboxDev/nxdk/blob/a00406664e67bb962da8269e80507e8eb7cf89e3/lib/nxdk/mount.c#L64-L67

This, without error checking in an nxdk-powered program's code, can lead people to think that the drive was unmounted properly, when really it wasn't. I don't know if this is intentional or a bug, but even if it is intentional, then I think making this return false when errors are encountered would be an improvement (however small), since programs can look if an error was encountered from the function's return value, instead of having to check for errors using WinAPI.

**Comment by mborgerson** [comment]
Fixed in f73fe046b03581d792d6f4b8d7c3f57338881b96
