### ISSUE TITLE
lld is not included in msys package list

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#39]
This is about the broken instructions in the readme for the Windows / msys build.

We also need the package "lld" (which aliases to "lld-svn"). Otherwise `lld-link` will not be found when running `make`.
*(I'm also not sure if we still need the "llvm" package.)*

However, even after installing "ldd" it will trigger issue #38 .
So possibly something else is (or already has been) messed up. @LukeUsher wrote the original documentation for Windows. So maybe he can shed some light on this?

I also wasn't sure which shell to use for running `make`: MSYS / MinGW 32 bit?

**Comment by mborgerson** [comment]
Fixed by #50
