### ISSUE TITLE
0ldskoo1 sample is confusing (red rectangle)

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#40]
The red rectangle is intended in the original code, but it's confusing users. Especially as we recommend 0ldskoo1 as the first sample to try.

Instead, we should hide the red box by default in the nxdk version.
Ideally we'd also change the message for the nxdk release.

**Comment by mborgerson** [comment]
I've got a textured/lit mesh demo waiting to be uploaded that does
basically the same thing as 0ldskoo1, but is easier to comprehend (similar
to my triangle sample). Will upload this soonish. In the meantime I think
the docs should start with the hello sample.

**Comment by jthecodebuilder** [comment]
Could there also be a tracker music player added (maybe at a later date since APU support is not the best atm)?

**Comment by JayFoxRox** [comment]
@jthecodebuilder please discuss this elsewhere. This issue is about the 0ldskoo1 sample and not about which samples we provide. If you care about audio stuff I'd recommend to look at #12 .

Anyhow, to avoid further derailing, this would be my response (I'll move it when a new issue about lack of samples is created):

[I've documented a bit of the APU on XboxDevWiki](http://xboxdevwiki.net/APU). However, I currently don't plan to add more stuff to nxdk as I'm primarily injecting my code through nxdk-rdt / xbdm / gdb. Most of my code is actually [written in python and runs remotely](https://github.com/JayFoxRox/xbox-tools/blob/master/python-scripts/dsp_homebrew.py).
I also have some more VP related code locally but it's all just hacked together to confim my documentation or to do read-only access.

I think there are far more important issues ( #13 , #15 , #35 ... ) than having functional code samples or even APU or GPU support (which don't necesarily have to be part of the toolchain as Xbox apps run in kernelmode anyway). There's also still some lack of documentation regarding some APU features (primarily streaming as I didn't care too much about that).
