### ISSUE TITLE
Using CMake or some other build system generator

### ISSUE THREAD

**Issue by jcn509** [XboxDev/nxdk#407]
Is there a particular reason that CMake (or some other build system generator) was not used for the nxdk? It seems to me that CMake would be a nicer option than make as it would make it easier to use nxdk with an IDE (Visual Studio has support for CMake out of the box) and it allows for integration with CTest which could be nice for some projects. I would be more than willing to try and convert the nxdk to CMake myself, but I don't want to go through the effort if it wouldn't be accepted because there is some reason that make was chosen over CMake.

**Comment by dracc** [comment]
JayFoxRox has (had?) a branch dedicated to accomplishing this goal. Might be a good starting point if you decide to pursue this.

As for reasons for not using cmake already, it seems to mostly boil down to personal preference and ease of maintenance.

**Comment by JayFoxRox** [comment]
This should have been resolved by #518 

Closed.

**Comment by RadWolfie** [comment]
Hi @JayFoxRox, not sure if you're aware but CMake toolchain in nxdk upstream is nonfunctional. Should be at least fully resolve in #631

**Comment by JayFoxRox** [comment]
Okay, however, current state (+ your branch) should be enough to resolve this issue.

Users can also check https://github.com/JayFoxRox/nxdk/pull/84 and https://github.com/JayFoxRox/nxdk/pull/74 for more options if upstream isn't good enough yet.

**Comment by ReenigneArcher** [comment]
This example helped me use cmake instead of make: https://github.com/Ryzee119/Xenium-Tools/blob/master/CMakeLists.txt

Take note of the extra commands needed in the ci workflow: https://github.com/Ryzee119/Xenium-Tools/blob/857464712cbee504098c590c09743edb44dae398/.github/workflows/build.yml#L19-L29
