### ISSUE TITLE
XBE Logo

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#420]
Currently the logo embedded in the XBE is that of OpenXDK. I've made a slight change to it to at least brand it with nxdk.

![image](https://user-images.githubusercontent.com/858612/104542015-bf01a480-55f0-11eb-99f2-57ed464d12e3.png)

```
AA 06 13 49 23 46 00 23 4D 33 0D 13 43 22 00 43 13 
C6 00 83 22 F0 D3 33 03 73 C3 33 0B 33 C3 73 05 73 
22 F0 E3 63 07 43 F3 22 00 F3 43 C6 00 B3 93 43 09 
23 43 F3 43 03 13 A3 F3 73 07 73 F3 A3 13 05 73 B3 
0B 13 43 C3 73 07 43 F3 22 00 F3 43 C6 00 B3 73 0F 
F3 43 07 53 E3 C3 63 C3 E3 53 09 73 B3 0F B3 73 03 
63 73 93 F3 7B 83 B3 D3 F3 43 C6 00 B3 73 0F F3 43 
09 13 E3 F3 E3 13 0B 73 B3 0F B3 73 03 83 B3 C3 F3 
BB D3 F5 B3 23 C6 00 B3 73 0F F3 43 07 33 C3 E3 73 
E3 C3 33 09 73 B3 0F B3 73 07 43 F3 0D 13 43 F3 43 
C6 00 B3 73 0F F3 43 05 73 F3 A3 13 03 13 A3 F3 73 
07 73 D3 7B 83 B3 E3 73 07 43 F3 22 00 F3 43 C6 00 
83 63 0F B3 33 03 63 E3 53 0B 53 E3 63 05 63 BF 75 
23 07 33 B3 22 00 B3 33 4E 01 13 0F 13 BE 06 03 05 
43 F3 36 00 73 B3 32 00 B3 73 0F F3 43 07 33 C3 E3 
73 E3 C3 33 09 73 B3 0F B3 73 07 43 F3 0D 13 43 F3 
43 22 00 F3 C3 A3 79 A3 C3 F3 05 43 F3 36 00 73 E3 
93 7B 93 B3 C3 07 B3 73 0F F3 43 05 73 F3 A3 13 03 
13 A3 F3 73 07 73 D3 7B 83 B3 E3 73 07 43 F3 22 00 
F3 43 22 00 53 73 83 B9 93 73 53 05 33 B3 36 00 43 
73 A3 BD 83 73 07 83 63 0F B3 33 03 63 E3 53 0B 53 
E3 63 05 63 BF 75 23 07 33 B3 22 00 B3 33 FA 00 13 0F 13 BE 06 03
```

**Comment by Apfel** [comment]
It'd be fun to see this as the default logo, but wouldn't it be cool to also allow declaring a custom Bitmap file as a parameter in a project's Makefile to use custom logos? i.e
```makefile
XBE_LOGO = custom.bmp
```

**Comment by mborgerson** [comment]
Agree, it should be changed. I prefer not to use that font as it has legibility issues (e.g. looks like NXOH, and branding is lowercase 'nxdk').

Also agree with @Apfel that it would be nice if it could be configurable (it is not a regular bitmap, it will require writing an encoder); however I'll settle for a changed logo first.

**Comment by Apfel** [comment]
> Also agree with @Apfel that it would be nice if it could be configurable (it is not a regular bitmap, it will require writing an encoder); however I'll settle for a changed logo first.

Not gonna lie, in case that'll be done, at this point I'd suggest rewriting CXBE just so it wouldn't be a pain to do that.
