### ISSUE TITLE
Improve network performance

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#460]
We need better network performance for various tasks:

- nv2a-trace (streaming/sending *a lot* of memory)
- xbe-loader (XISO streaming)
- Realtime games (enet for example, which is already ported in https://github.com/JayFoxRox/nxdk/pull/84)
- Audio communication over network when #438 hits and XBL Communicator support lands

This is a collection of unfinished work by @thrimbor in that area:

- https://github.com/thrimbor/nxdk/commits/net_improvements_clean
- https://github.com/thrimbor/nxdk/commits/net_improvements
- https://github.com/thrimbor/nxdk/commits/nvnetdrv
- https://github.com/thrimbor/nxdk/commits/pktdrv_perf

I'm not sure what the plans are.

I also checked, and we are already on latest stable lwip.

**Comment by dracc** [comment]
Not to mention NevolutionX ftp/sntp/...

Less important when xbe-loader becomes performant but still nice-to-have IMO.

**Comment by Ryzee119** [comment]
For visibility, Thrimbor and I have been working more on nvnetdrv. https://github.com/Ryzee119/nxdk/tree/nvnetdrv/lib/nvnetdrv
I have been using it for some time and is working very well for me with excellent performance >90mbit/s normally

Might just need a few more tweaks

**Comment by dracc** [comment]
> For visibility, Thrimbor and I have been working more on nvnetdrv. https://github.com/Ryzee119/nxdk/tree/nvnetdrv/lib/nvnetdrv I have been using it for some time and is working very well for me with excellent performance >90mbit/s normally
> 
> Might just need a few more tweaks

Care to create a draft PR? Great work that's a bit hard to keep track of for outsiders. :)
