### ISSUE TITLE
Review signedness and type of xboxkrnl/winapi `STATUS_` macros

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#479]
It looks like the type for `STATUS_ACCESS_VIOLATION` is incorrect, which leads to issues when using it in a switch case.

Code like this:

```c
char const* Message(DWORD exceptionCode)
{
  switch (exceptionCode)
  {
  [...]
  case EXCEPTION_ACCESS_VIOLATION:
  [...]
  }
  [...]
```

```
<project>: warning: implicit conversion changes signedness: 'NTSTATUS' (aka 'long') to 'DWORD' (aka 'unsigned long') [-Wsign-conversion]
  case EXCEPTION_ACCESS_VIOLATION:
       ^~~~~~~~~~~~~~~~~~~~~~~~~~
nxdk/lib/winapi/minwinbase.h:34:44: note: expanded from macro 'EXCEPTION_ACCESS_VIOLATION'
#define EXCEPTION_ACCESS_VIOLATION         STATUS_ACCESS_VIOLATION
                                           ^~~~~~~~~~~~~~~~~~~~~~~
nxdk/lib/xboxkrnl/ntstatus.h:24:34: note: expanded from macro 'STATUS_ACCESS_VIOLATION'
#define STATUS_ACCESS_VIOLATION ((NTSTATUS)0xC0000005L)
<project>: fatal error: case value evaluates to -1073741819, which cannot be narrowed to type 'DWORD' (aka 'unsigned long') [-Wc++11-narrowing]

```

**Comment by thrimbor** [comment]
The type of the `NTSTATUS`es is correct, but looks like there's a cast missing from the exception constants, judging from [ReactOS's version](https://doxygen.reactos.org/db/dbb/winbase_8h_source.html#l00308)

**Comment by JayFoxRox** [comment]
Interestingly I can also quickly find "(C) Microsoft" which doesn't cast exception codes to `DWORD`, so I'm not sure how this is supposed to work; I believe I had also found headers which *did not* have the `NTSTATUS` cast.
Unfortunately I don't have a Windows SDK installed right now, to check what MS does where it matters (in their MSVS / Windows SDK distribution).

**Comment by thrimbor** [comment]
Ok, this is weird. Our `NTSTATUS` is `LONG`, which is the same as in VS2019. Our status constants are all `NTSTATUS`, but in VS2019, they're `DWORD`s instead, which is a typedef for `unsigned long`. That's why they don't use a cast for their `EXCEPTION_` constants.
I'm not sure why they're using different types here, but I guess it won't hurt if we do it the same way?

**Comment by JayFoxRox** [comment]
Thanks for looking into it.
We should mimic what MS does. If they don't use `NTSTATUS` casts then we shouldn't do it either.
