### ISSUE TITLE
XBE header magic too small

### ISSUE THREAD

**Issue by dracc** [XboxDev/nxdk#493]
https://github.com/XboxDev/nxdk/blob/a7a5ecff1d5b6b6af187c4de013ddf26509851b5/lib/winapi/winnt.h#L286

The value of this one is `0x48454258` on retail titles, a full DWORD long, not just WORD.

**Comment by GXTX** [comment]
When we launch an application, what in the xbe header does the kernel actually verify/read?

**Comment by dracc** [comment]
You're right. I shouldn't have edited the adress of the header. Ofc it
should be 0x10000 still.

**Comment by GXTX** [comment]
I'll assume the kernel only checks magic.
