### ISSUE TITLE
MakeFile Error

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [XboxDev/nxdk#519]
Hey, so i installed nxdk and i tried to create my first program but i have a problem, when i try to compile my program it gives me this error, the error says make: *** No targets specified and no makefile found.  Stop.
so is there a way you can help me please!

**Comment by NeoGeoFreak2004** [comment]
Now it is saying this error, the error says: Makefile:7: /home/anthony/Documents/Xbox/Test/../../Makefile: No such file or directory
make: *** No rule to make target '/home/anthony/Documents/Xbox/Test/../../Makefile'.  Stop.

**Comment by NeoGeoFreak2004** [comment]
im trying to build a c++ program its just a test program.

**Comment by dracc** [comment]
> Now it is saying this error, the error says: Makefile:7: /home/anthony/Documents/Xbox/Test/../../Makefile: No such file or directory
> make: *** No rule to make target '/home/anthony/Documents/Xbox/Test/../../Makefile'. Stop.

The problem is right there. On line 7 in your `Makefile`, you're referencing a file that doesn't exist. Classic copy/paste error.
Try editing one of the samples available in `nxdk/samples` instead, and/or read up on [GNU Make](https://www.gnu.org/software/make/manual/make.pdf). 
Either way this is not an nxdk issue but user error and should be closed.

**Comment by NeoGeoFreak2004** [comment]
Update: so I want to create a makefile for nxdk but how do I edit the makefile to reference the directory were the source code is?

**Comment by kosmas12** [comment]
Good evening!

This would seem to be one of the many times you've posted here about errors when compiling. These are not errors with nxdk itself, but rather with your configuration, so please ask on our Discord server when you need help with such things. This is the wrong place to ask. We've said this many times, so please stop posting here and instead join our Discord and ask for help there.
