### ISSUE TITLE
SHADER_OBJS deps on mingw64

### ISSUE THREAD

**Issue by jimmsta** [XboxDev/nxdk#52]
Compiling the 0ldskoo1 sample on mingw64 by simply typing make fails, as the vs.inl and ps.inl files are not compiled properly. Compiling them directly works. The deps are incorrect for the shaders. 

Removing the nxdk Makefile's "/debug" flag seems to also fix compilation of other samples. Not sure this is related or not.

**Comment by JayFoxRox** [comment]
To make this easier to find in search:

This causes:

```
samples/0ldskoo1/graphics.c:444:14: fatal error: 'vs.inl' file not found
```

And it can be worked-around by doing `make vs.inl` before doing `make` again.

**Comment by GXTX** [comment]
Sample was removed in #139. Recommend closing.
