### ISSUE TITLE
READ_PORT_BUFFER_* WRITE_PORT_BUFFER_* and friends have wrong type hints

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#537]
The typehints in `xboxkrnl.h` for these functions are wrong leading to warnings while building projects with them.

See my info script for correct usage.

**Comment by thrimbor** [comment]
The types in the function signature match Microsoft's declaration in `wdm.h` and `miniport.h`, as well as ReactOS's declarations. The kernel code it applies to is functionally equivalent to ReactOS's implementation and byte-for-byte the same as Microsoft's implementation in `hal.dll` on Windows 7 x86.

Please clarify what you think is wrong.

**Comment by GXTX** [comment]
Hi, please see my complaints in your software development channel on you discord.

**Comment by thrimbor** [comment]
The chat history doesn't provide what I asked for. Given what I wrote above, please clarify what you think is wrong.

**Comment by GXTX** [comment]
Hi @thrimbor, the chat convo I had with Matt about this issue should accurately describe the problem. I implore you to attempt to use these functions as their type hints suggest, your Xbox will not like it.

Due to reasons I unfortunately don't have time these days to help figure out why this is broken, but looking at my info script (perhaps I never shared this with you? other maintainers should have access and can give you a link), or again testing these functions yourself, you will see what is and isn't working.

Thanks for the future fix!

**Comment by thrimbor** [comment]
Please refrain from opening issues if you are unwilling to even describe your actual problem.

Since this is not the first case of you demonstrating uncooperative behavior on XboxDev repositories, I feel obliged to inform you that continuing this pattern will possibly lead to getting blocked from interacting with these repositories in the future.

Should you have a legitimate problem, please feel free to create a more constructive issue, ideally after consulting a guide describing how to create a good GitHub issue.

**Comment by GXTX** [comment]
> demonstrating uncooperative behavior

I seem to just have this issue with you. I'm not sure why. The conversation with Matt on Discord accurately displays what the issue is and what the correct types should be. I'm not in that server so I cannot give you the logs of it, however you are.

This is a legitimate issue, and it's unfortunate you've decided to close it instead of investigate as the maintainer. Hopefully this issue being left unresolved does not create confusion for future users of nxdk.

**Comment by GXTX** [comment]
@thrimbor this issue was fixed in CXBX-R. Please consider looking at their changes and reevaluating this issue. Thanks.

**Comment by dracc** [comment]
cxbx-reloaded/cxbx-reloaded#2318 for context.

**Comment by Ryzee119** [comment]
```
//Read port 0xEF on OpenXenium chip
PUCHAR port = (PUCHAR)0x00EF;
UCHAR rx = 0;
READ_PORT_BUFFER_UCHAR(port, &rx, 1);
printf("Reg EF read: %02x\n", rx);
```
Works fine.. whats the issue here?

Matches [Reactos](https://github.com/reactos/reactos-deprecated-gitsvn-dont-use/blob/6530b899b37ecbfed47ffdb1093b6f7cd1708d60/reactos/hal/halx86/generic/portio.c#L24-L29) and [Windows](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-read_port_buffer_uchar) docs.

I agree with Thrimbor on this one.

**Comment by GXTX** [comment]
And this will crash your box.
```
ULONG pci_buff;
ULONG pci_addr = 0x8000036C;
ULONG pci_port1 = 0xCF8;
ULONG pci_port2 = 0xCFC;
ULONG count = 1;
WRITE_PORT_BUFFER_ULONG(&pci_port1, &pci_addr, 1);
READ_PORT_BUFFER_ULONG(&pci_port2, &pci_buff, &count);
```

**Comment by abaire** [comment]
It seems the decision has been made to stay aligned with the approach Windows takes, but I think it'd be useful to at least provide some explanation in the context of the declaration for folks who go looking when they run into problems.

Would simply adding the Windows parameter explanation as a doccomment resolve this in your mind (taken as a given that changing the type signature is off the table)? If not, @GXTX can you suggest an alternative comment that would explain away the confusion from your perspective?

**Comment by GXTX** [comment]
There's multiple things going in here. Both `Port` and `Count` are issues. Does it really make sense to have `Count` be a pointer in one function and not another? 

And I don't think there's any confusion here, the `Port` requires a pointer *to* a unsigned long which doesn't work but if you give it a unsigned long it functions as expected.

**Comment by abaire** [comment]
I agree with you that there are multiple issues here, which makes it harder to resolve.

----
`Count` being a `PULONG`:
```
XBAPI VOID NTAPI READ_PORT_BUFFER_ULONG
(
    IN PULONG Port,
    OUT PULONG Buffer,
    IN PULONG Count
);
```

This does not match the [Windows documentation](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-read_port_buffer_ulong) so I think there is an argument to be made in favor of fixing that.

-----

`Port` clearly is confusion generating though. From my perspective the type could imply that it takes a pointer to a ulong  containing the port number, but the documentation states: `Specifies the port address, which must be a mapped memory range in I/O space.`. This is pretty ambiguous but can be taken to imply that the value actually is the port address i.e. some MMIO value.

I'd argue that in this case it'd be reasonable to just improve the documentation, perhaps including an example. Something like:

`Port: Pointer to the memory mapped I/O address of the port. E.g., to access port "0xCF8", this parameter should be (PULONG)0xCF8.`

and obviously the remainder of the parameters should be documented as well.

**Comment by thrimbor** [comment]
> `Count` being a `PULONG`:
> 
> ```
> XBAPI VOID NTAPI READ_PORT_BUFFER_ULONG
> (
>     IN PULONG Port,
>     OUT PULONG Buffer,
>     IN PULONG Count
> );
> ```

You're right, the type of the `Count` parameter on this one function is indeed incorrect. Thanks for going through the effort of double-checking, this is what should've been contained in the issue description from the very beginning :+1: 

> `Port` clearly is confusion generating though. From my perspective the type could imply that it takes a pointer to a ulong containing the port number, but the documentation states: `Specifies the port address, which must be a mapped memory range in I/O space.`. This is pretty ambiguous but can be taken to imply that the value actually is the port address i.e. some MMIO value.

Yeah it's a bit strangely worded. Nowadays nobody seems to call ports addresses, but MS stuck to the terminology of memory address space and I/O address space. For nxdk I'd recommend adding a Doxygen-style comment (like some other function declarations have), but in case anybody wants to improve MS's documentation, they're accepting pull requests for it nowadays: https://github.com/MicrosoftDocs/windows-driver-docs-ddi/blob/staging/wdk-ddi-src/content/wdm/nf-wdm-read_port_buffer_ulong.md
