### ISSUE TITLE
`winapi/winnt.h` causes warning with `-pedantic` enabled

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#547]
```
/home/wsl/Projects/nxdk/lib/winapi/winnt.h:10:16: warning: extension used [-Wlanguage-extension-token]
typedef signed __int64 LONG64, *PLONG64;
```

Is this fixable without disabling `pedantic`?

**Comment by JayFoxRox** [comment]
Such headers should potentially be included using `-isystem` (if not already happening); I'd assume this will disable such warnings.
