### ISSUE TITLE
Building `NXDK_ONLY=y` with LTO creates xbe that crash

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#552]
Building nxdk libs with LTO seem to generate xbes that crash/hang. Tested on hardware.

```
wsl@DESKTOP:~/Test/nxdk$ eval $(bin/activate -s) NXDK_ONLY=y LTO=y make -j8
[...]
wsl@DESKTOP:~/Test/nxdk$ cd samples/hello
wsl@DESKTOP:~/Test/nxdk/samples/hello$ eval $(../../bin/activate -s) LTO=y make
```

Building only the sample as LTO functions correctly.

I had hoped to use this to reduce xbe size (although it's not a real issue). The smallest size is 104KB with `-O3` on just the application, ~65KB with LTO on both libs and application, and ~49KB with LTO & `-O3` on both.

**Comment by thrimbor** [comment]
I can't reproduce this on Arch with LLVM 13.0.1, the hello sample works fine for me on hardware and in xemu. What's your LLVM version and distro? Are your submodules (PDCLib specifically) up to date?

**Comment by GXTX** [comment]
WSL1
```
Ubuntu 20.04.4 LTS \n \l
llvm | 1:10.0-50~exp1
```

Full clone using the example in the readme.

**Comment by GXTX** [comment]
Upgraded to WSL2 same problem. Perhaps an issue with llvm version?
