### ISSUE TITLE
lld-link: Command not found (Ubuntu 18.04)

### ISSUE THREAD

**Issue by mborgerson** [XboxDev/nxdk#56]
Installed executable name is `lld-link-6.0`. We can:
* Change to the `-6.0` name, or
* Detect which version to use, or
* Ask user to update Makefile or create a symlink

**Comment by dracc** [comment]
I thought I was slick running `pkexec update-alternatives --install /usr/bin/lld-link lld-link /usr/bin/lld-link-6.0 10`, but I can see why you wouldn't want to recommend that.

Probably best to try to detect what version to use, but I'm not sure how to.

**Comment by JayFoxRox** [comment]
> Change to the -6.0 name

Sounds like a bad idea, because it will change with every update, even if there's no changes to the basic CLI frontend

> Detect which version to use

Sounds good, if this can be easily automated and doesn't add highly distribution specific code.

> Ask user to update Makefile or create a symlink

This is the worst idea, because it works around package manager.
Asking users to look for updates, or report issues could be a good idea in error cases.

---

* How do other projects solve this?
* Is there some feature in Ubuntu which already solves this?
    If I remember correctly, you can install multiple window environments and then use something Ubuntu (or Debian) specific, similar to what was shown by @dracc (which would create the respective symlinks, and also keep track in the package manager).


That said, if @dracc adds a way to undo that step in his post, it might be a good workaround while we are looking for a solution (I'm not sure how exactly pkexec works, or if it's a sane step - so how to revert / undo it, should be documented).

**Comment by thrimbor** [comment]
Why not use `lld -flavor link`, like the Makefile does on macOS?

**Comment by dracc** [comment]
Great catch, @thrimbor! I tested the command you suggested in Debian, works fine. I propose we roll with that!

**Comment by Ernegien** [comment]
I think this is still broken in Ubuntu 18.04 LTS. Here's what I get when trying to build a sample:

```mike@MJD0020:~/Projects/nxdk/samples/0ldskoo1$ make
[ LD       ] main.exe
make: lld: Command not found
/home/mike/Projects/nxdk/samples/0ldskoo1/../../Makefile:104: recipe for target 'main.exe' failed
make: *** [main.exe] Error 127

mike@MJD0020:~/Projects/nxdk/samples/0ldskoo1$ ld
ld: no input files
mike@MJD0020:~/Projects/nxdk/samples/0ldskoo1$ lld

Command 'lld' not found, did you mean:

  command 'lxd' from snap lxd (3.7)
  command 'ld' from deb binutils
  command 'ldd' from deb libc-bin
  command 'lxd' from deb lxd
  command 'bld' from deb bld
  command 'llt' from deb storebackup
  command 'lzd' from deb lzd
  command 'lli' from deb llvm-runtime
  command 'gld' from deb postfix-gld
  command 'lid' from deb id-utils
  command 'llc' from deb llvm
  command 'lpd' from deb lpr
  command 'lpd' from deb lprng
  command 'wld' from deb wcc

See 'snap info <snapname>' for additional versions.

mike@MJD0020:~/Projects/nxdk/samples/0ldskoo1$ lld-link
lld-link: command not found
mike@MJD0020:~/Projects/nxdk/samples/0ldskoo1$ lld-6.0
lld is a generic driver.
Invoke ld.lld (Unix), ld (macOS) or lld-link (Windows) instead.
mike@MJD0020:~/Projects/nxdk/samples/0ldskoo1$ lld-link-6.0
lld-link-6.0: error: no input files```

**Comment by thrimbor** [comment]
I cannot reproduce this.
![screenshot_20181202_150722](https://user-images.githubusercontent.com/1339483/49340707-0791ba00-f644-11e8-9863-cffad2e222fc.png)

**Comment by Ernegien** [comment]
You're right, I must not have done my due diligence. Although to my defense, [LLVM installation instructions](http://apt.llvm.org/) don't specifically mention 'apt install lld' as part of the process, perhaps we should be more explicit in the nxdk README?

![image](https://user-images.githubusercontent.com/382923/49342979-9cd28580-f627-11e8-8062-da1785f6f139.png)
