### ISSUE TITLE
xaudio sample not working with XQEMU

### ISSUE THREAD

**Issue by andjnewb** [XboxDev/nxdk#572]
This may just be an issues on my end, but here is my setup.
BIOS: xbox-4627_debug.bin
MCPX: mouse_rev0.bin
RAM: 64 MB
It built successfully so I'm not sure what the issue is, the xbox intro plays fine.

**Comment by ProtoByter** [comment]
I would recommend trying xemu, since afaik xqemu isn't maintained, and xemu is (it's a fork of xqemu maintained by mborgerson)

**Comment by Ryzee119** [comment]
Please attempt on hardware before raising an issue. This is likely an emulation issue

**Comment by andjnewb** [comment]
> I would recommend trying xemu, since afaik xqemu isn't maintained, and xemu is (it's a fork of xqemu maintained by mborgerson)

I mistakenly said that that I was using XQEMU but I'm actually using XEMU, my bad lol. I figured it was but I'll close the issue since it does work on real hardware as I just tested.
