### ISSUE TITLE
makefile compilling issue

### ISSUE THREAD

**Issue by NeoGeoFreak2004** [XboxDev/nxdk#574]
hey yall, so anyways i followed the guide on how to create a makefile for nxdk, but here is the problem, when i type in make to the terminal, it gives me a error. the error says: Makefile:8: /Makefile: No such file or directory
make: *** No rule to make target '/Makefile'.  Stop.
i think im going to give up so can you guys please help me!

**Comment by thrimbor** [comment]
This is the third time you open an invalid issue on this repo (https://github.com/XboxDev/nxdk/issues/519, https://github.com/XboxDev/nxdk/issues/522).
This issue tracker is not for conversation. If you have a question about nxdk, our Discord is the appropriate way to contact us. That said, your question has almost nothing to do with nxdk, and you've excluded all information that could be used to help you.

As you have done this before, including evading all questions that have been asked in return, I can only assume you are doing this on purpose, so this is your final warning:
If you open another invalid issue on this repo, you will get blocked from interacting with it.
