### ISSUE TITLE
error: no type named 'align_val_t' in namespace 'std'

### ISSUE THREAD

**Issue by glebm** [XboxDev/nxdk#587]
```
/opt/nxdk/lib/libcxx/include/new:205:102: error: no type named 'align_val_t' in namespace 'std'
_LIBCPP_NODISCARD_AFTER_CXX17 _LIBCPP_OVERRIDABLE_FUNC_VIS void* operator new(std::size_t __sz, std::align_val_t) _THROW_BAD_ALLOC;
```

**Comment by glebm** [comment]
This is probably an issue for https://github.com/XboxDev/nxdk-libcxx

**Comment by kosmas12** [comment]
Good day!

Are you sure that your CXXFLAGS are correct and that you are compiling using C++ 17? Thanks!

**Comment by glebm** [comment]
This is the generated build command:

> /opt/nxdk/bin/nxdk-cxx -D_POSIX_C_SOURCE=200809L -I/home/gleb/devilutionX/build-xbox/_deps/libfmt-src/include -std=c++20 -o CMakeFiles/fmt.dir/src/format.cc.obj -c /home/gleb/devilutionX/build-xbox/_deps/libfmt-src/src/format.cc

**Comment by kosmas12** [comment]
Huh, it seems like `-std=c++20` should work, not sure what's up, I'm lead to believe we have a huge part of the STL, I'll try using that type on a minimal sample now too, just to make sure it's actually an issue on our end.

**Comment by kosmas12** [comment]
Just tried it too, it seems that I can't get the compiler to recognize that type either.

**Comment by glebm** [comment]
I've managed to fix it in https://github.com/XboxDev/nxdk-libcxx/pull/8 (I have no idea what I'm doing but this works)

**Comment by kosmas12** [comment]
Thanks for fixing it, a maintainer will most likely review it and merge soon
