### ISSUE TITLE
Nxdk equivalent for IOCP or epoll?

### ISSUE THREAD

**Issue by c9d5e1** [XboxDev/nxdk#623]
Does Nxdk offer a solution like IOCP or epoll for I/O related operations?

**Comment by JayFoxRox** [comment]
It depends on what you need:
- What use-case [X-Y problem avoidance]?
- API requirements [custom, POSIX, win32, or something specific might be required when porting something]?
- What type of file handles does it have to support [disk-i/o, networking or some peripheral access]?

---

IOCP and epoll do not exist in nxdk.

However, there's asynchronous I/O in the kernel. But nxdk also doesn't support overlapped I/O for the user-space-like abstraction:
https://github.com/XboxDev/nxdk/blob/fb1e5a5b2e99eb276008a51e4409f7d3d0d6a6d8/lib/winapi/fileio.c#L106-L107

You can still manually reimplement those functions on the kernel API and wait for IO events to complete like this:
https://github.com/XboxDev/nxdk/blob/fb1e5a5b2e99eb276008a51e4409f7d3d0d6a6d8/lib/winapi/fileio.c#L113-L120

However, at least one of the Xbox filesystems (either FATX or XISO, I don't remember which one) didn't perform too well when I tried it (or I used it incorrectly?).

IOCP also exists in the kernel, but there's no user-space API for it in nxdk:
https://github.com/XboxDev/nxdk/blob/fb1e5a5b2e99eb276008a51e4409f7d3d0d6a6d8/lib/xboxkrnl/xboxkrnl.h#L3040-L3046

I'm not sure about networking and the USB stack either (check lwip documentation for networking instead / read the USB code).

**Comment by c9d5e1** [comment]
Use case: Writing a task scheduler/executor.
API requirements: No specific requirements.
What type of file handles does it have to support: Preferably, everything.

Specifically, what I'm actually trying to do is to link a static Rust library into some C code and to give Rust access to some sort of I/O polling mechanism for its asynchronous code. I'd preferably want to be able to use any kind of file descriptor (disk-i/o, networking, xbox controller and memory card slots) with this Rust library.
