### ISSUE TITLE
SDL_GameControllerOpen fails to open controller with LTO enabled

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#624]
`SDL_GameControllerOpen` fails to init a controller when both nxdk and the application are built with `LTO=y`

**Comment by thrimbor** [comment]
Moved the issue as it seems to be a problem with the USB code, not specifically SDL.

I haven't investigated this fully, in case someone wants to continue this is what I found and posted on Discord:
> Something weird is going on with get_ticks in libusbohci here. Putting __attribute__((optnone))  in front of it fixes the issue, but it's unlikely to be the function's fault, it's probably something triggered by inlining it
