### ISSUE TITLE
Add pbgl to libs

### ISSUE THREAD

**Issue by PQCraft** [XboxDev/nxdk#650]
Repo URL: https://github.com/fgsfdsfgs/pbgl

**Comment by thrimbor** [comment]
Imho this is already covered by https://github.com/XboxDev/nxdk/issues/42 - some OpenGL(-ish) implementation will eventually be provided, but not necessarily pbgl (or xgu-gl). There are also underlying issues in pbkit (the hardcoded buffers, the way it handles the fifo) and integration issues (egl? SDL compatibility?) to be solved.

**Comment by JayFoxRox** [comment]
These are typically referenced in https://github.com/XboxDev/nxdk/wiki/Projects-using-nxdk#libraries now.

We generally try to make build-system nxdk compatible, so we no longer have to compile and distribute libs as part of nxdk (especially not as part of the nxdk makefile which currently builds both: 1. nxdk itself, and 2. the app).
