### ISSUE TITLE
nxMountDrive does not support multi-char drives

### ISSUE THREAD

**Issue by GXTX** [XboxDev/nxdk#673]
Chihiro mounts

```
mbfs:\
mbcom:\
mbsys:\
mbrom0:\
mbrom1:\
mbupdate:\
```

**Comment by thrimbor** [comment]
That's a design choice, it's meant to be simple. I'm inclined to close this as invalid, as we have no real reason to imitate what Chihiro games do in nxdk.

**Comment by GXTX** [comment]
> as we have no real reason to imitate what Chihiro games do in nxdk

To be clear, it's not the games which set-up these drives, it's the kernel itself.

![image](https://github.com/user-attachments/assets/6a51f907-bf3c-4bdf-9d14-6d35e37bbe84)

One of the goals of XboxDev, from my view, is that of hardware compatibility -- this brings *us* closer to that. Of course, one can just call the underlying `IoCreateSymbolicLink`, but it would be nice to have an option.

**Comment by thrimbor** [comment]
> > as we have no real reason to imitate what Chihiro games do in nxdk
> 
> To be clear, it's not the games which set-up these drives, it's the kernel itself.

In that case I don't even know what you want with `nxMountDrive`. It's not intended to touch kernel stuff, like `cdrom:`

> One of the goals of XboxDev, from my view, is that of hardware compatibility -- this brings _us_ closer to that.
Huh? What does any of this have to do with hw compat?

> Of course, one can just call the underlying `IoCreateSymbolicLink`, but it would be nice to have an option. And it's a 3 character change to support this.

Most importantly, it's an API-break. `nxMountDrive` was never meant to replace `IoCreateSymbolicLink` or handle all its use cases, it's meant to be a convenient way for must use cases: Setting up Windows-like drive letters.

**Comment by GXTX** [comment]
I can see where this is going. So I'll simply close instead of letting it sit rotting without additional comment.

> In that case I don't even know what you want with nxMountDrive

Simply needed a helper function to mount a drive: `mbrom0:` symlinked to `\Device\MediaBoard\Partition3`. I'm working on some things which, eventually, will not require the Chihiro kernel which utilize a nxdk based loader.

> Huh? What does any of this have to do with hw compat?

It's a situation found on hardware *retail* hardware. Imo, nxdk should *support* this.

**Comment by JayFoxRox** [comment]
I think it's a fair use-case, and there should probably be an API like `nxMountDevice` or something like that (or update the existing API and have users deal with breakage, although it would likely require a lot more memory management to reserve the new strings etc. = complexity).

Alternatively, this could be in a Chihiro-specific driver lib (instead of nxdk).
After all, Chihiro will also need a bunch of other changes / drivers anyway.
