### ISSUE TITLE
xboxrt: Legacy wcsncpy and strncpy functions do not fill exactly n bytes

### ISSUE THREAD

**Issue by Fisherman166** [XboxDev/nxdk#81]
Legacy wcsncpy (and strncpy) functions in xboxrt do not match the definition of wcsncpy. Specifically, we do not fill exactly n bytes of data. A similar issue exists with strncpy. See the man page for more information:

Exactly n wide characters are written at dest. If the length wcslen(src) is smaller than n, the remaining wide characters in the array pointed to by dest are filled with null wide characters.

From @JayFoxRox 
We currently don't fill exactly n bytes (and neither could we, because our users don't respect that - see wcscpy which calls with SIZE_MAX)

*Edited by JayFoxRox: `wcspy` should not be affected by most of this (except that it's using `wcsncpy` poorly); However, `strncpy` is also affected by the exact same issue (in a different part of the code).*

**Comment by JayFoxRox** [comment]
Also affects strncpy. So if we fix one of them, we should also fix the other one.

The issue description and title should be improved to reflect this. That was also my original intention when I requested an issue: keep consistency in our codebase and avoid fixing only one of them. My mistake: I should have been more clear.

**Comment by Fisherman166** [comment]
Updated to reflect the whole issue.
