### ISSUE TITLE
SDL requires `_exit` function

### ISSUE THREAD

**Issue by JayFoxRox** [XboxDev/nxdk#97]
SDL requires an `_exit` function.
This is a bit odd, and it looks like a calling convention mismatch for `exit`.

I don't know wether it should be an handler that handles exits, or, if it's a function that's being called to force an exit.

Our use in sample code is inconsistent, too:

In the sdl sample, it's used like an `atexit` handler, that also forces an `exit` through reboot itself:

https://github.com/XboxDev/nxdk/blob/192c770aab063c65d8999d7508a60f3b2f5a290f/samples/sdl/main.c#L21-L28

*(Also called by application code)*

In the sdl_ttf sample, it's used like a dummy and no "exit" of any kind is performed:

https://github.com/XboxDev/nxdk/blob/192c770aab063c65d8999d7508a60f3b2f5a290f/samples/sdl_ttf/main.c#L12-L14

*(Unused by application code)*

---

Someone should investigate, fix this behaviour (probably shouldn't require hacks in application code) and make the sample code consistent.

**Comment by dracc** [comment]
This was fixed in xboxdev/nxdk-sdl#4 and #103 - issue should be closed. :+1:
